# coding: utf-8

"""
    LedgerLens.ai Platform API

    Financial Document Q&A Assistant API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from openapi_server.models.dashboard_update import DashboardUpdate
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DashboardResponse(BaseModel):
    """
    DashboardResponse
    """ # noqa: E501
    watchlist_count: StrictInt
    new_reports: StrictInt
    pending_processing: StrictInt
    recent_updates: List[DashboardUpdate]
    __properties: ClassVar[List[str]] = ["watchlist_count", "new_reports", "pending_processing", "recent_updates"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DashboardResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recent_updates (list)
        _items = []
        if self.recent_updates:
            for _item in self.recent_updates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['recent_updates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DashboardResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "watchlist_count": obj.get("watchlist_count"),
            "new_reports": obj.get("new_reports"),
            "pending_processing": obj.get("pending_processing"),
            "recent_updates": [DashboardUpdate.from_dict(_item) for _item in obj.get("recent_updates")] if obj.get("recent_updates") is not None else None
        })
        return _obj


