{{- if and .Values.secret.create (not .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger-lens-api.fullname" . }}
  labels:
    {{- include "ledger-lens-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}