# coding: utf-8

"""
    LedgerLens.ai Platform API

    Financial Document Q&A Assistant API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.analyst_reports_api import router as AnalystReportsApiRouter
from openapi_server.apis.auth_api import router as AuthApiRouter
from openapi_server.apis.chat_api import router as ChatApiRouter
from openapi_server.apis.companies_api import router as CompaniesApiRouter
from openapi_server.apis.compare_api import router as CompareApiRouter
from openapi_server.apis.dashboard_api import router as DashboardApiRouter
from openapi_server.apis.documents_api import router as DocumentsApiRouter
from openapi_server.apis.mcp_api import router as MCPApiRouter
from openapi_server.apis.rag_api import router as RAGApiRouter
from openapi_server.apis.scheduler_api import router as SchedulerApiRouter
from openapi_server.apis.watchlist_api import router as WatchlistApiRouter

app = FastAPI(
    title="LedgerLens.ai Platform API",
    description="Financial Document Q&amp;A Assistant API",
    version="1.0.0",
)

app.include_router(AnalystReportsApiRouter)
app.include_router(AuthApiRouter)
app.include_router(ChatApiRouter)
app.include_router(CompaniesApiRouter)
app.include_router(CompareApiRouter)
app.include_router(DashboardApiRouter)
app.include_router(DocumentsApiRouter)
app.include_router(MCPApiRouter)
app.include_router(RAGApiRouter)
app.include_router(SchedulerApiRouter)
app.include_router(WatchlistApiRouter)
